############## define directories that we work with #############
# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/ksr/Desktop/contact_localization/efri/"
#  "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/epilepsy/"
#  "/home/adam2392/Documents/Dropbox/phd_research/data/neuroimaging_results/epilepsy/"
  '/Users/adam2392/Downloads/neuroimg/'

derivatives_output_dir:
#    "/home/ksr/Desktop/contact_localization/efri/raw_msb/"
# "/Users/ChesterHuynh/sarmalab/contact_localization_proj/rawdata"
  "/Users/adam2392/Downloads/neuroimg/derivatives/"
#  "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/epilepsy/raw/"
#  "/home/adam2392/Documents/Dropbox/phd_research/data/neuroimaging_results/epilepsy/derivatives/"

############# define list of files to run this for #############
patients:
  [
#    "PublicDataset",
    'la02',
#    "la04",
#      'efri02',
#     'efri06',
#      'efri10',
#      'efri13',
#     'efri07',
#     'efri09',
#      'efri14',
#     'efri18',
#      'efri20',
]

blender_path: # type in 'which blender' in command line
  "/usr/bin/blender/"

