############## define directories that we work with #############
# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/ksr/Desktop/contact_localization/efri/"
#  "/Users/adam2392/Dropbox/phd_research/data/neuroimaging_results/epilepsy/"
  "/home/adam2392/hdd2/epilepsy_bids/"
#  '/Users/adam2392/Downloads/neuroimg/'

derivatives_output_dir:
#    "/home/ksr/Desktop/contact_localization/efri/raw_msb/"
# "/Users/ChesterHuynh/sarmalab/contact_localization_proj/rawdata"
#  "/Users/adam2392/Downloads/neuroimg/derivatives/"
  "/home/adam2392/hdd2/epilepsy_bids/derivatives/"

############# define list of files to run this for #############
patients:
  [
#    "PublicDataset",
#    'la01',
    'la09',
    'la02',
   'la03',
   "la04",'la05','la06','la07','la08','la10',
   'la11','la12', 'la13', 'la15',
   'la16','la17',
   'la21', 'la22', 'la23', 'la24',
   'nl01', 'nl04', 'nl05',  'nl07', 'nl08', 'nl09', 'nl10',
   'nl12', 'nl13', 'nl14', 'nl15', 'nl16', 'nl17', 'nl18', 'nl19', 'nl20', 'nl21', 'nl22', 'nl23',
   'tvb1', 'tvb2', 'tvb5', 'tvb7', 'tvb8', 'tvb11', 'tvb12', 'tvb14', 'tvb17', 'tvb18', 'tvb19', 'tvb23',
#    'nl02', 'nl06','nl11',
#    'tvb27', 'tvb28', 'tvb29',
    # 'nl24', 'la27', 'la28', 'la29', 'la31',
#  'la02','umf004',
]

blender_path: # type in 'which blender' in command line
  "/usr/bin/blender/"
