# define directories that we work with
rawdatadir:
  "/home/adam2392/hdd/data/neuroimaging/raw"
   # "/Users/adam2392/Downloads/neuroimaging/"

finaloutput_datadir:
  "/home/adam2392/hdd/data/neuroimaging/freesurfer_output/outputfiles/"

fs_outputdatadir:
 "/home/adam2392/hdd/data/neuroimaging/freesurfer_output/"
  # "/Users/adam2392/Downloads/neuroimaging/freesurfer_output/"

outputplotsdir:
 "/home/adam2392/hdd/data/neuroimaging/freesurfer_output/figures/"
  # "/Users/adam2392/Downloads/neuroimaging/freesurfer_output/figures/"

# define list of files to run this for
patients:
  [
#    'la02',
#    'la17',
#    'la23',
#        'la14',
   'la03',
#   'la04',
#   'la05',
#   'la06',
#   'la07',
#    'la08',
#    'la09',
#    'la10',
#    'la11',
#    'la12',
#    'la13',
#    'la15',
#    'la16',
#    'la21',
#    'la22',
#    'la24',
#    'nl01',
#    'nl02',
#    'nl03',
#    'nl04',
#    'nl05',
#    'nl06',
#    'nl07',
#    'nl08',
#    'nl09',
#    'nl10',
#    'nl11',
#    'nl12',
#   'nl11',
#   'nl12',
#   'nl13',
#   'nl14',
#   'nl15',
#   'nl16',
#   'nl17',
#   'nl18',
#   'nl19',
#  'nl20'
]