name: seek
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
- python>=3.6
- pip=20
- mkl
- numpy>=1.14
- scipy>=1.1.0
- scikit-learn>=0.19.2
- pandas>=0.23.4
- mne>=0.19.0
- mne-bids>=0.3
- joblib>=0.14
- matplotlib
- seaborn
- click
- natsort
- xlrd
- tqdm
- pybv
- nibabel
- scikit-image
- flask
- pip:
  - pybids>=0.10

